version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-clinica-dental
    environment:
      MYSQL_ROOT_PASSWORD: Katya00&
      MYSQL_DATABASE: clinica_dental
    ports:
      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pKatya00&"]
      interval: 30s
      timeout: 10s
      retries: 5

#volumes:
#  mysql_data:
